apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: happy-speller
  app.kubernetes.io/name: happy-speller
  app.kubernetes.io/component: web
  app.kubernetes.io/part-of: happy-speller-platform