apiVersion: v1
kind: Service
metadata:
  name: happy-speller
  labels:
    app: happy-speller
spec:
  type: ClusterIP
  selector:
    app: happy-speller
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http