- op: replace
  path: /spec/template/spec/containers/0
  value:
    name: happy-speller
    image: nginx:alpine
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: ENVIRONMENT
      value: "staging"
    - name: LOG_LEVEL
      value: "info"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "80"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 3
      failureThreshold: 3
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 101
      runAsGroup: 101
    volumeMounts:
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-run
      mountPath: /var/run
- op: replace
  path: /spec/template/spec/securityContext
  value:
    fsGroup: 101
    runAsNonRoot: true
    runAsUser: 101
- op: add
  path: /spec/template/spec/volumes
  value:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
