apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: happy-speller-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: happy-speller-apps
spec:
  project: default
  source:
    repoURL: https://github.com/amineatya/happy-speller-platform.git  # Update with your actual repo
    targetRevision: HEAD
    path: gitops/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true