apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: happy-speller-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: happy-speller
    app.kubernetes.io/environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/amineatya/happy-speller-platform.git  # Update with your actual repo
    targetRevision: HEAD
    path: gitops/environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: happy-speller-staging
  syncPolicy:
    # Manual sync for staging - requires approval
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10