apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-speller
  namespace: demo
  labels:
    app: happy-speller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: happy-speller
  template:
    metadata:
      labels:
        app: happy-speller
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: happy-speller
        image: node:20-alpine
        command: ["sh", "-c"]
        args:
        - |
          cd /app
          npm install --only=production
          exec node server.js
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        workingDir: /app
        volumeMounts:
        - name: app-source
          mountPath: /app
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-source
        configMap:
          name: happy-speller-app
---
apiVersion: v1
kind: Service
metadata:
  name: happy-speller
  namespace: demo
spec:
  selector:
    app: happy-speller
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: happy-speller-lb
  namespace: demo
spec:
  selector:
    app: happy-speller
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
