---
- name: Configure Jenkins for Happy Speller
  hosts: localhost
  connection: local
  vars:
    jenkins_url: "http://192.168.50.247:8080"
    jenkins_user: "amine"
    jenkins_token: "{{ lookup('env', 'JENKINS_TOKEN') }}"
    gitea_token: "{{ lookup('env', 'GITEA_TOKEN') }}"
    minio_access_key: "{{ lookup('env', 'MINIO_ACCESS_KEY') }}"
    minio_secret_key: "{{ lookup('env', 'MINIO_SECRET_KEY') }}"
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  
  tasks:
  - name: Install required Jenkins plugins
    jenkins_plugin:
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_token }}"
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - pipeline
      - credentials
      - kubernetes
      - blueocean
      - junit
      - htmlpublisher
      - ansible
      - workflow-aggregator
  
  - name: Create Gitea credentials in Jenkins
    jenkins_credentials:
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_token }}"
      name: "gitea-token"
      description: "Gitea API token"
      credential_type: username_password
      username: "amine"
      password: "{{ gitea_token }}"
      state: present
  
  - name: Create MinIO credentials in Jenkins
    jenkins_credentials:
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_token }}"
      name: "minio-creds"
      description: "MinIO access credentials"
      credential_type: username_password
      username: "{{ minio_access_key }}"
      password: "{{ minio_secret_key }}"
      state: present
  
  - name: Create kubeconfig credential in Jenkins
    jenkins_credentials:
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_token }}"
      name: "kubeconfig"
      description: "Kubernetes config file"
      credential_type: file
      file: "{{ kubeconfig }}"
      state: present
  
  - name: Create Jenkins pipeline job
    jenkins_job:
      url: "{{ jenkins_url }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_token }}"
      name: "happy-speller-pipeline"
      config: |
        <?xml version='1.1' encoding='UTF-8'?>
        <project>
          <description>CI/CD pipeline for Happy Speller application</description>
          <keepDependencies>false</keepDependencies>
          <properties>
            <com.coravy.hudson.plugins.github.GithubProjectProperty>
              <projectUrl>http://192.168.50.130:3000/amine/happy-speller-platform</projectUrl>
            </com.coravy.hudson.plugins.github.GithubProjectProperty>
            <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersConfig>
              <hudson.triggers.SCMTrigger>
                <spec>H/5 * * * *</spec>
                <ignorePostCommitHooks>false</ignorePostCommitHooks>
              </hudson.triggers.SCMTrigger>
            </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersConfig>
          </properties>
          <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.92">
            <scm class="hudson.plugins.git.GitSCM" plugin="git@4.8.3">
              <configVersion>2</configVersion>
              <userRemoteConfigs>
                <hudson.plugins.git.UserRemoteConfig>
                  <url>http://192.168.50.130:3000/amine/happy-speller-platform.git</url>
                  <credentialsId>gitea-token</credentialsId>
                </hudson.plugins.git.UserRemoteConfig>
              </userRemoteConfigs>
              <branches>
                <hudson.plugins.git.BranchSpec>
                  <name>*/main</name>
                </hudson.plugins.git.BranchSpec>
              </branches>
              <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
              <submoduleCfg class="list"/>
              <extensions/>
            </scm>
            <scriptPath>Jenkinsfile</scriptPath>
            <lightweight>true</lightweight>
          </definition>
          <triggers/>
          <disabled>false</disabled>
        </project>
      state: present
