- op: replace
  path: /spec/template/spec/containers/0
  value:
    name: happy-speller
    image: httpd:alpine
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: ENVIRONMENT
      value: "prod"
    - name: LOG_LEVEL
      value: "warn"
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "80"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 33
      runAsGroup: 33
- op: replace
  path: /spec/template/spec/securityContext
  value:
    fsGroup: 33
    runAsNonRoot: true
    runAsUser: 33
- op: replace
  path: /spec/strategy
  value:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
