apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-speller
spec:
  template:
    spec:
      containers:
      - name: happy-speller
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: LOG_LEVEL
          value: "debug"
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
